"resources"
{
	"materials/vgui/maps/test_slaughterball/area_indoors.vmt" "file"
	"materials/vgui/maps/test_slaughterball/area_indoors.vtf" "file"
	"materials/vgui/maps/test_slaughterball/area_outdoors.vmt" "file"
	"materials/vgui/maps/test_slaughterball/area_outdoors.vtf" "file"
	"materials/vgui/maps/test_slaughterball/location_elevated.vmt" "file"
	"materials/vgui/maps/test_slaughterball/location_elevated.vtf" "file"
	"materials/vgui/maps/test_slaughterball/location_sewerlid.vmt" "file"
	"materials/vgui/maps/test_slaughterball/location_sewerlid.vtf" "file"
	"materials/vgui/maps/test_slaughterball/location_square.vmt" "file"
	"materials/vgui/maps/test_slaughterball/location_square.vtf" "file"
	"materials/vgui/maps/test_slaughterball/location_twisted.vmt" "file"
	"materials/vgui/maps/test_slaughterball/location_twisted.vtf" "file"
	"materials/vgui/maps/test_slaughterball/location_warehouse.vmt" "file"
	"materials/vgui/maps/test_slaughterball/location_warehouse.vtf" "file"
	"materials/vgui/slaughterball/icon_team_2.vmt" "file"
	"materials/vgui/slaughterball/icon_team_3.vmt" "file"
	"materials/vgui/slaughterball/icon_team_4.vmt" "file"
	"materials/vgui/slaughterball/icon_team_5.vmt" "file"
	"materials/vgui/slaughterball/icon_team_blue.vtf" "file"
	"materials/vgui/slaughterball/icon_team_green.vtf" "file"
	"materials/vgui/slaughterball/icon_team_red.vtf" "file"
	"materials/vgui/slaughterball/icon_team_yellow.vtf" "file"
	"materials/vgui/slaughterball/location_default.vmt" "file"
	"materials/vgui/slaughterball/location_default.vtf" "file"
}
